mode: train
lmdb: True
dry_run: false
rgb_dir: './datasets/rgb'
lmdb_dir:  './datasets/lmdb'
dataset_json_folder: './preprocessing/dataset_json'
SWA: False
save_avg: True
log_dir: ./logs/training/